### ISSUE TITLE
Move code out of master and into own or other, existing branch

### ISSUE THREAD

**Issue by mdbray** [cryo3d/cryo3d#2]
Guys, pleaseee do not just commit straight into master.  All code in master is supposed to be "ready for deployment" and we should/ are going to use code reviews before any code gets merged into master.

**Comment by kbeamnsidc** [comment]
@mdbray +1. You've probably already talked about this, but just in case, here's a good reference to what @mdbray is talking about doing (I think): https://guides.github.com/introduction/flow/. This is basically what our dev teams practice here. There are other ways to go, but this is pretty simple and effective.

I'm not trying to influence what you do (it's your choice), just wanted to provide some input.

**Comment by mdbray** [comment]
@shadowfax6894 can you please move committed code out of master and into a separate branch?  Thanks :)

**Comment by shadowfax6894** [comment]
@mdbray done

**Comment by mdbray** [comment]
+1
Thanks @shadowfax6894 !  I'll mark as resolved and close this.
